### ISSUE TITLE
build failure  error code ELIFECYCLE

### ISSUE THREAD

**Issue by berl** [pwinston/webmon#8]
tried to install by following the instructions and got this error from  `make build` :
very likely a beginner error with my environment, but any pointers would help!

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.14.9
3 info using node@v8.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @~prebuild: @
6 info lifecycle @~build: @
7 verbose lifecycle @~build: unsafe-perm in lifecycle true
8 verbose lifecycle @~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/brian/work/webmon/js/node_modules/.bin:/Users/brian/anaconda2/envs/starfish/bin:/Users/brian/anaconda2/condabin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
9 verbose lifecycle @~build: CWD: /Users/brian/work/webmon/js
10 silly lifecycle @~build: Args: [ '-c', 'node build' ]
11 silly lifecycle @~build: Returned: code: 1  signal: null
12 info lifecycle @~build: Failed to exec build script
13 verbose stack Error: @ build: `node build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @
15 verbose cwd /Users/brian/work/webmon/js
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v8.11.1
19 verbose npm  v6.14.9
20 error code ELIFECYCLE
21 error errno 1
22 error @ build: `node build`
22 error Exit status 1
23 error Failed at the @ build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by pwinston** [comment]
Thanks for the error report. But nothing jumps out at me. Nothing in the stack seems related our stuff.

I'd say nuke your `node_modules` dir but if this was from scratch, that's not it.

Any ideas @manzt ?

**Comment by manzt** [comment]
Hmm it looks like you are using an old version of Node (`v8.11.1`). Could you try upgrading to Node 12 or later?

**Comment by pwinston** [comment]
If that fixes it, I can add it to the README/requirements. I've never paid much attention to node versions. But it make sense there is some minimum. Thanks @manzt!

**Comment by berl** [comment]
yep that was it. thanks @manzt and @pwinston !

**Comment by pwinston** [comment]
Great. I updated the README. Please update the README or ping me on Zulip if you run into any issues that you have to puzzle over. I'm sure there will be some! Thanks, @berl and @manzt.
